# Travis CI config for Speller
language: objective-c
osx_image: xcode8.1
xcode_project: Speller.xcodeproj

env:
  global:
  - PROJECT=Speller.xcodeproj
  - IOS_SCHEME="Speller-iOS"
  - IOS_SDK=iphonesimulator10.1
  - MACOS_SCHEME="Speller-macOS"
  - MACOS_SDK=macosx10.12
  - WATCHOS_SCHEME="Speller-watchOS"
  - WATCHOS_SDK=watchsimulator3.1
  - TVOS_SCHEME="Speller-tvOS"
  - TVOS_SDK=appletvsimulator10.0

  matrix:
    - DESTINATION="arch=x86_64"                             SCHEME="$MACOS_SCHEME"    SDK="$MACOS_SDK"    RUN_TESTS="YES"
    - DESTINATION="OS=10.1,name=iPhone 6"                   SCHEME="$IOS_SCHEME"      SDK="$IOS_SDK"      RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"             SCHEME="$TVOS_SCHEME"     SDK="$TVOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=3.1,name=Apple Watch Series 2 - 38mm" SCHEME="$WATCHOS_SCHEME"  SDK="$WATCHOS_SDK"  RUN_TESTS="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email: false
