//
//  SpellingAlphabet.swift
//  Speller
//
//  Created by Jean-Étienne on 7/11/16.
//  Copyright © 2016 Jean-Étienne. All rights reserved.
//

import Foundation

typealias SpellingAlphabetContent = [Character: CodeWordCollection]

public enum SpellingAlphabet {

    case InternationalRadiotelephony

    case InternationalRadiotelephonyNumbers

    case USFinancial

    case LAPD

    case French

    case BasicLatin

    case Latin1Supplement

    case LatinExtendedA

    case LatinExtendedB


    internal func load() -> SpellingAlphabetContent {
        switch self {
        case .LatinExtendedB:
            return self.loadLatinExtendedB()
        case .LatinExtendedA:
            return self.loadLatinExtendedA()
        case .Latin1Supplement:
            return self.loadLatin1Supplement()
        case .BasicLatin:
            return self.loadBasicLatin()
        case .French:
            return self.loadFrench()
        case .LAPD:
            return self.loadLAPD()
        case .USFinancial:
            return self.loadUSFinancial()
        case .InternationalRadiotelephonyNumbers:
            return self.loadInternationalRadiotelephonyNumbers()
        case .InternationalRadiotelephony:
            fallthrough
        default:
            return self.loadInternationalRadiotelephony()
        }
    }

    // MARK: - Private methods
    private func loadInternationalRadiotelephony() -> SpellingAlphabetContent {
        return ["A": "Alfa",        "B": "Bravo",
                "C": "Charlie",     "D": "Delta",
                "E": "Echo",        "F": "Foxtrot",
                "G": "Golf",        "H": "Hotel",
                "I": "India",       "J": "Juliett",
                "K": "Kilo",        "L": "Lima",
                "M": "Mike",        "N": "November",
                "O": "Oscar",       "P": "Papa",
                "Q": "Quebec",      "R": "Romeo",
                "S": "Sierra",      "T": "Tango",
                "U": "Uniform",     "V": "Victor",
                "W": "Whiskey",     "X": "X-ray",
                "Y": "Yankee",      "Z": "Zulu"]
    }

    private func loadInternationalRadiotelephonyNumbers() -> SpellingAlphabetContent {
        return ["1": "Unaone",      "2": "Bissotwo",
                "3": "Terrathree",  "4": "Kartefour",
                "5": "Pantafive",   "6": "Soxisix",
                "7": "Setteseven",  "8": "Oktoeight",
                "9": "Novenine",    "0": "Nadazero"]
    }

    private func loadUSFinancial() -> SpellingAlphabetContent {
        return ["A": "Adam",    "B": "Bob",
                "C": "Carol",   "D": "David",
                "E": "Eddie",   "F": "Frank",
                "G": "George",  "H": "Harry",
                "I": "Ike",     "J": "Jim",
                "K": "Kenny",   "L": "Larry",
                "M": "Mary",    "N": "Nancy",
                "O": "Oliver",  "P": "Peter",
                "Q": "Quincy",  "R": "Roger",
                "S": "Sam",     "T": "Thomas",
                "U": "Uncle",   "V": "Vincent",
                "W": "William", "X": "Xavier",
                "Y": "Yogi",    "Z": "Zachary"]
    }

    private func loadLAPD() -> SpellingAlphabetContent {
        return ["A": "Adam",    "B": "Boy",
                "C": "Charles", "D": "David",
                "E": "Edward",  "F": "Frank",
                "G": "George",  "H": "Henry",
                "I": "Ida",     "J": "John",
                "K": "King",    "L": "Lincoln",
                "M": "Mary",    "N": "Nora",
                "O": "Ocean",   "P": "Paul",
                "Q": "Queen",   "R": "Robert",
                "S": "Sam",     "T": "Tom",
                "U": "Union",   "V": "Victor",
                "W": "William", "X": "X-ray",
                "Y": "Young",   "Z": "Zebra"]
    }

    private func loadFrench() -> SpellingAlphabetContent {
        return ["A": "Anatole",     "B": "Berthe",
                "C": "Célestin",    "D": "Désiré",
                "E": "Eugène",      "F": "François",
                "G": "Gaston",      "H": "Henri",
                "I": "Irma",        "J": "Joseph",
                "K": "Kléber",      "L": "Louis",
                "M": "Marcel",      "N": "Nicolas",
                "O": "Oscar",       "P": "Pierre",
                "Q": "Quintal",     "R": "Raoul",
                "S": "Suzanne",     "T": "Thérèse",
                "U": "Ursule",      "V": "Victor",
                "W": "William",     "X": "Xavier",
                "Y": "Yvonne",      "Z": "Zoé"]
    }

    private func loadBasicLatin() -> SpellingAlphabetContent {
        return [" " : "Space",
                "!" : "Exclamation mark",
                "\"": "Quotation mark",
                "#" : ["Number sign", "Hashtag", "Octothorpe", "Sharp"],
                "$" : "Dollar sign",
                "%" : "Percent sign",
                "&" : "Ampersand",
                "'" : "Apostrophe",
                "(" : "Left parenthesis",
                ")" : "Right parenthesis",
                "*" : "Asterisk",
                "+" : "Plus sign",
                "," : "Comma",
                "-" : ["Hyphen", "minus"],
                "." : "Full stop",
                "/" : "Slash",
                "0" : "Digit Zero",
                "1" : "Digit One",
                "2" : "Digit Two",
                "3" : "Digit Three",
                "4" : "Digit Four",
                "5" : "Digit Five",
                "6" : "Digit Six",
                "7" : "Digit Seven",
                "8" : "Digit Eight",
                "9" : "Digit Nine",
                ":" : "Colon",
                ";" : "Semicolon",
                "<" : "Less-than sign",
                "=" : "Equal sign",
                ">" : "Greater-than sign",
                "?" : "Question mark",
                "@" : "At sign",
                "A" : "Latin capital letter A",
                "B" : "Latin capital letter B",
                "C" : "Latin capital letter C",
                "D" : "Latin capital letter D",
                "E" : "Latin capital letter E",
                "F" : "Latin capital letter F",
                "G" : "Latin capital letter G",
                "H" : "Latin capital letter H",
                "I" : "Latin capital letter I",
                "J" : "Latin capital letter J",
                "K" : "Latin capital letter K",
                "L" : "Latin capital letter L",
                "M" : "Latin capital letter M",
                "N" : "Latin capital letter N",
                "O" : "Latin capital letter O",
                "P" : "Latin capital letter P",
                "Q" : "Latin capital letter Q",
                "R" : "Latin capital letter R",
                "S" : "Latin capital letter S",
                "T" : "Latin capital letter T",
                "U" : "Latin capital letter U",
                "V" : "Latin capital letter V",
                "W" : "Latin capital letter W",
                "X" : "Latin capital letter X",
                "Y" : "Latin capital letter Y",
                "Z" : "Latin capital letter Z",
                "[" : "Left square bracket",
                "\\": "Backslash",
                "]" : "Right square bracket",
                "^" : "Circumflex accent",
                "_" : ["Underscore", "Low line"],
                "`" : "Grave accent",
                "a" : "Latin small Letter A",
                "b" : "Latin small Letter B",
                "c" : "Latin small Letter C",
                "d" : "Latin small Letter D",
                "e" : "Latin small Letter E",
                "f" : "Latin small Letter F",
                "g" : "Latin small Letter G",
                "h" : "Latin small Letter H",
                "i" : "Latin small Letter I",
                "j" : "Latin small Letter J",
                "k" : "Latin small Letter K",
                "l" : "Latin small Letter L",
                "m" : "Latin small Letter M",
                "n" : "Latin small Letter N",
                "o" : "Latin small Letter O",
                "p" : "Latin small Letter P",
                "q" : "Latin small Letter Q",
                "r" : "Latin small Letter R",
                "s" : "Latin small Letter S",
                "t" : "Latin small Letter T",
                "u" : "Latin small Letter U",
                "v" : "Latin small Letter V",
                "w" : "Latin small Letter W",
                "x" : "Latin small Letter X",
                "y" : "Latin small Letter Y",
                "z" : "Latin small Letter Z",
                "{" : "Left curly bracket",
                "|" : "Vertical bar",
                "}" : "Right curly bracket",
                "~" : "Tilde"]
    }

    private func loadLatin1Supplement() -> SpellingAlphabetContent {
        return ["¡": "Inverted Exclamation Mark",
                "¢": "Cent sign",
                "£": "Pound sign",
                "¤": "Currency sign",
                "¥": "Yen sign",
                "¦": "Broken bar",
                "§": "Section sign",
                "¨": "Diaeresis (Umlaut)",
                "©": "Copyright sign",
                "ª": "Feminine ordinal indicator",
                "«": "Left-pointing double angle quotation mark",
                "¬": "Not sign",
                "0": "Soft hyphen",
                "®": "Registered sign",
                "¯": "Macron",
                "°": "Degree symbol",
                "±": "Plus-minus sign",
                "²": "Superscript two",
                "³": "Superscript three",
                "´": "Acute accent",
                "µ": "Micro sign",
                "¶": "Pilcrow sign",
                "·": "Middle dot",
                "¸": "Cedilla",
                "¹": "Superscript one",
                "º": "Masculine ordinal indicator",
                "»": "Right-pointing double angle quotation mark",
                "¼": "Vulgar fraction one quarter",
                "½": "Vulgar fraction one half",
                "¾": "Vulgar fraction three quarters",
                "¿": "Inverted question mark",
                "À": "Latin capital letter A with grave",
                "Á": "Latin capital letter A with acute",
                "Â": "Latin capital letter A with circumflex",
                "Ã": "Latin capital letter A with tilde",
                "Ä": "Latin capital letter A with diaeresis",
                "Å": "Latin capital letter A with ring above",
                "Æ": "Latin capital letter Æ",
                "Ç": "Latin capital letter C with cedilla",
                "È": "Latin capital letter E with grave",
                "É": "Latin capital letter E with acute",
                "Ê": "Latin capital letter E with circumflex",
                "Ë": "Latin capital letter E with diaeresis",
                "Ì": "Latin capital letter I with grave",
                "Í": "Latin capital letter I with acute",
                "Î": "Latin capital letter I with circumflex",
                "Ï": "Latin capital letter I with diaeresis",
                "Ð": "Latin capital letter Eth",
                "Ñ": "Latin capital letter N with tilde",
                "Ò": "Latin capital letter O with grave",
                "Ó": "Latin capital letter O with acute",
                "Ô": "Latin capital letter O with circumflex",
                "Õ": "Latin capital letter O with tilde",
                "Ö": "Latin capital letter O with diaeresis",
                "×": "Multiplication sign",
                "Ø": "Latin capital letter O with stroke",
                "Ù": "Latin capital letter U with grave",
                "Ú": "Latin capital letter U with acute",
                "Û": "Latin capital letter U with circumflex",
                "Ü": "Latin capital letter U with diaeresis",
                "Ý": "Latin capital letter Y with acute",
                "Þ": "Latin capital letter Thorn",
                "ß": "Latin small letter sharp S",
                "à": "Latin small letter A with grave",
                "á": "Latin small letter A with acute",
                "â": "Latin small letter A with circumflex",
                "ã": "Latin small letter A with tilde",
                "ä": "Latin small letter A with diaeresis",
                "å": "Latin small letter A with ring above",
                "æ": "Latin small letter Æ",
                "ç": "Latin small letter C with cedilla",
                "è": "Latin small letter E with grave",
                "é": "Latin small letter E with acute",
                "ê": "Latin small letter E with circumflex",
                "ë": "Latin small letter E with diaeresis",
                "ì": "Latin small letter I with grave",
                "í": "Latin small letter I with acute",
                "î": "Latin small letter I with circumflex",
                "ï": "Latin small letter I with diaeresis",
                "ð": "Latin small letter Eth",
                "ñ": "Latin small letter N with tilde",
                "ò": "Latin small letter O with grave",
                "ó": "Latin small letter O with acute",
                "ô": "Latin small letter O with circumflex",
                "õ": "Latin small letter O with tilde",
                "ö": "Latin small letter O with diaeresis",
                "÷": "Division sign",
                "ø": "Latin small letter O with stroke",
                "ù": "Latin small letter U with grave",
                "ú": "Latin small letter U with acute",
                "û": "Latin small letter U with circumflex",
                "ü": "Latin small letter U with diaeresis",
                "ý": "Latin small letter Y with acute",
                "þ": "Latin small letter Thorn",
                "ÿ": "Latin small letter Y with diaeresis"]
    }

    private func loadLatinExtendedA() -> SpellingAlphabetContent {
        return ["Ā": "Latin capital letter A with macron",
                "ā": "Latin small letter A with macron",
                "Ă": "Latin capital letter A with breve",
                "ă": "Latin small letter A with breve",
                "Ą": "Latin capital letter A with ogonek",
                "ą": "Latin small letter A with ogonek",
                "Ć": "Latin capital letter C with acute",
                "ć": "Latin small letter C with acute",
                "Ĉ": "Latin capital letter C with circumflex",
                "ĉ": "Latin small letter C with circumflex",
                "Ċ": "Latin capital letter C with dot above",
                "ċ": "Latin small letter C with dot above",
                "Č": "Latin capital letter C with caron",
                "č": "Latin small letter C with caron",
                "Ď": "Latin capital letter D with caron",
                "ď": "Latin small letter D with caron",
                "Đ": "Latin capital letter D with stroke",
                "đ": "Latin small letter D with stroke",
                "Ē": "Latin capital letter E with macron",
                "ē": "Latin small letter E with macron",
                "Ĕ": "Latin capital letter E with breve",
                "ĕ": "Latin small letter E with breve",
                "Ė": "Latin capital letter E with dot above",
                "ė": "Latin small letter E with dot above",
                "Ę": "Latin capital letter E with ogonek",
                "ę": "Latin small letter E with ogonek",
                "Ě": "Latin capital letter E with caron",
                "ě": "Latin small letter E with caron",
                "Ĝ": "Latin capital letter G with circumflex",
                "ĝ": "Latin small letter G with circumflex",
                "Ğ": "Latin capital letter G with breve",
                "ğ": "Latin small letter G with breve",
                "Ġ": "Latin capital letter G with dot above",
                "ġ": "Latin small letter G with dot above",
                "Ģ": "Latin capital letter G with cedilla",
                "ģ": "Latin small letter G with cedilla",
                "Ĥ": "Latin capital letter H with circumflex",
                "ĥ": "Latin small letter H with circumflex",
                "Ħ": "Latin capital letter H with stroke",
                "ħ": "Latin small letter H with stroke",
                "Ĩ": "Latin capital letter I with tilde",
                "ĩ": "Latin small letter I with tilde",
                "Ī": "Latin capital letter I with macron",
                "ī": "Latin small letter I with macron",
                "Ĭ": "Latin capital letter I with breve",
                "ĭ": "Latin small letter I with breve",
                "Į": "Latin capital letter I with ogonek",
                "į": "Latin small letter I with ogonek",
                "İ": "Latin capital letter I with dot above",
                "ı": "Latin small letter dotless I",
                "Ĳ": "Latin Capital Ligature IJ",
                "ĳ": "Latin Small Ligature IJ",
                "Ĵ": "Latin capital letter J with circumflex",
                "ĵ": "Latin small letter J with circumflex",
                "Ķ": "Latin capital letter K with cedilla",
                "ķ": "Latin small letter K with cedilla",
                "ĸ": "Latin small letter Kra",
                "Ĺ": "Latin capital letter L with acute",
                "ĺ": "Latin small letter L with acute",
                "Ļ": "Latin capital letter L with cedilla",
                "ļ": "Latin small letter L with cedilla",
                "Ľ": "Latin capital letter L with caron",
                "ľ": "Latin small letter L with caron",
                "Ŀ": "Latin capital letter L with middle dot",
                "ŀ": "Latin small letter L with middle dot",
                "Ł": "Latin capital letter L with stroke",
                "ł": "Latin small letter L with stroke",
                "Ń": "Latin capital letter N with acute",
                "ń": "Latin small letter N with acute",
                "Ņ": "Latin capital letter N with cedilla",
                "ņ": "Latin small letter N with cedilla",
                "Ň": "Latin capital letter N with caron",
                "ň": "Latin small letter N with caron",
                "ŉ": "Latin small letter N preceded by apostrophe[1]",
                "Ŋ": "Latin capital letter Eng",
                "ŋ": "Latin small letter Eng",
                "Ō": "Latin capital letter O with macron",
                "ō": "Latin small letter O with macron",
                "Ŏ": "Latin capital letter O with breve",
                "ŏ": "Latin small letter O with breve",
                "Ő": "Latin capital letter O with double acute",
                "ő": "Latin small letter O with double acute",
                "Œ": "Latin Capital Ligature OE",
                "œ": "Latin Small Ligature OE",
                "Ŕ": "Latin capital letter R with acute",
                "ŕ": "Latin small letter R with acute",
                "Ŗ": "Latin capital letter R with cedilla",
                "ŗ": "Latin small letter R with cedilla",
                "Ř": "Latin capital letter R with caron",
                "ř": "Latin small letter R with caron",
                "Ś": "Latin capital letter S with acute",
                "ś": "Latin small letter S with acute",
                "Ŝ": "Latin capital letter S with circumflex",
                "ŝ": "Latin small letter S with circumflex",
                "Ş": "Latin capital letter S with cedilla",
                "ş": "Latin small letter S with cedilla",
                "Š": "Latin capital letter S with caron",
                "š": "Latin small letter S with caron",
                "Ţ": "Latin capital letter T with cedilla",
                "ţ": "Latin small letter T with cedilla",
                "Ť": "Latin capital letter T with caron",
                "ť": "Latin small letter T with caron",
                "Ŧ": "Latin capital letter T with stroke",
                "ŧ": "Latin small letter T with stroke",
                "Ũ": "Latin capital letter U with tilde",
                "ũ": "Latin small letter U with tilde",
                "Ū": "Latin capital letter U with macron",
                "ū": "Latin small letter U with macron",
                "Ŭ": "Latin capital letter U with breve",
                "ŭ": "Latin small letter U with breve",
                "Ů": "Latin capital letter U with ring above",
                "ů": "Latin small letter U with ring above",
                "Ű": "Latin capital letter U with double acute",
                "ű": "Latin small letter U with double acute",
                "Ų": "Latin capital letter U with ogonek",
                "ų": "Latin small letter U with ogonek",
                "Ŵ": "Latin capital letter W with circumflex",
                "ŵ": "Latin small letter W with circumflex",
                "Ŷ": "Latin capital letter Y with circumflex",
                "ŷ": "Latin small letter Y with circumflex",
                "Ÿ": "Latin capital letter Y with diaeresis",
                "Ź": "Latin capital letter Z with acute",
                "ź": "Latin small letter Z with acute",
                "Ż": "Latin capital letter Z with dot above",
                "ż": "Latin small letter Z with dot above",
                "Ž": "Latin capital letter Z with caron",
                "ž": "Latin small letter Z with caron",
                "ſ": "Latin small letter long S"]
    }

    private func loadLatinExtendedB() -> SpellingAlphabetContent {
        return ["ƀ": "Latin small letter B with stroke",
                "Ɓ": "Latin capital letter B with hook",
                "Ƃ": "Latin capital letter B with top bar",
                "ƃ": "Latin small letter B with top bar",
                "Ƅ": "Latin capital letter Tone Six",
                "ƅ": "Latin small letter Tone Six",
                "Ɔ": "Latin capital letter Open O",
                "Ƈ": "Latin capital letter C with hook",
                "ƈ": "Latin small letter C with hook",
                "Ɖ": "Latin capital letter African D",
                "Ɗ": "Latin capital letter D with hook",
                "Ƌ": "Latin capital letter D with top bar",
                "ƌ": "Latin small letter D with top bar",
                "ƍ": "Latin small letter Turned Delta",
                "Ǝ": "Latin capital letter Reversed E",
                "Ə": "Latin capital letter Schwa",
                "Ɛ": "Latin capital letter Open E",
                "Ƒ": "Latin capital letter F with hook",
                "ƒ": "Latin small letter F with hook",
                "Ɠ": "Latin capital letter G with hook",
                "Ɣ": "Latin capital letter Gamma",
                "ƕ": "Latin small letter HV",
                "Ɩ": "Latin capital letter Iota",
                "Ɨ": "Latin capital letter I with stroke",
                "Ƙ": "Latin capital letter K with hook",
                "ƙ": "Latin small letter K with hook",
                "ƚ": "Latin small letter L with bar",
                "ƛ": "Latin small letter Lambda with stroke",
                "Ɯ": "Latin capital letter Turned M",
                "Ɲ": "Latin capital letter N with left hook",
                "ƞ": "Latin small letter N with long right leg",
                "Ɵ": "Latin capital letter O with middle tilde",
                "Ơ": "Latin capital letter O with horn",
                "ơ": "Latin small letter O with horn",
                "Ƣ": ["Latin capital letter OI", "Latin capital letter Gha)"],
                "ƣ": ["Latin small letter OI", "Latin small letter Gha)"],
                "Ƥ": "Latin capital letter P with hook",
                "ƥ": "Latin small letter P with hook",
                "Ʀ": "Latin Letter YR",
                "Ƨ": "Latin capital letter Tone Two",
                "ƨ": "Latin small letter Tone Two",
                "Ʃ": "Latin capital letter Esh",
                "ƪ": "Latin Letter Reversed Esh Loop",
                "ƫ": "Latin small letter T with palatal hook",
                "Ƭ": "Latin capital letter T with hook",
                "ƭ": "Latin small letter T with hook",
                "Ʈ": "Latin capital letter T with retroflex hook",
                "Ư": "Latin capital letter U with horn",
                "ư": "Latin small letter U with horn",
                "Ʊ": "Latin capital letter Upsilon",
                "Ʋ": "Latin capital letter V with hook",
                "Ƴ": "Latin capital letter Y with hook",
                "ƴ": "Latin small letter Y with hook",
                "Ƶ": "Latin capital letter Z with stroke",
                "ƶ": "Latin small letter Z with stroke",
                "Ʒ": "Latin capital letter Ezh",
                "Ƹ": "Latin capital letter Ezh reversed",
                "ƹ": "Latin small letter Ezh reversed",
                "ƺ": "Latin small letter Ezh with tail",
                "ƻ": "Latin Letter Two with stroke",
                "Ƽ": "Latin capital letter Tone Five",
                "ƽ": "Latin small letter Tone Five",
                "ƾ": "Latin Letter Inverted Glottal Stop with stroke",
                "ƿ": "Latin Letter Wynn",
                "ǀ": "Latin Letter Dental Click",
                "ǁ": "Latin Letter Lateral Click",
                "ǂ": "Latin Letter Alveolar Click",
                "ǃ": "Latin Letter Retroflex Click",
                "Ǆ": "Latin capital letter DZ with caron",
                "ǅ": "Latin capital letter D with small letter Z with caron",
                "ǆ": "Latin small letter DZ with caron",
                "Ǉ": "Latin capital letter LJ",
                "ǈ": "Latin capital letter L with small letter J",
                "ǉ": "Latin small letter LJ",
                "Ǌ": "Latin capital letter NJ",
                "ǋ": "Latin capital letter N with small letter J",
                "ǌ": "Latin small letter NJ",
                "Ǎ": "Latin capital letter A with caron",
                "ǎ": "Latin small letter A with caron",
                "Ǐ": "Latin capital letter I with caron",
                "ǐ": "Latin small letter I with caron",
                "Ǒ": "Latin capital letter O with caron",
                "ǒ": "Latin small letter O with caron",
                "Ǔ": "Latin capital letter U with caron",
                "ǔ": "Latin small letter U with caron",
                "Ǖ": "Latin capital letter U with diaeresis and macron",
                "ǖ": "Latin small letter U with diaeresis and macron",
                "Ǘ": "Latin capital letter U with diaeresis and acute",
                "ǘ": "Latin small letter U with diaeresis and acute",
                "Ǚ": "Latin capital letter U with diaeresis and caron",
                "ǚ": "Latin small letter U with diaeresis and caron",
                "Ǜ": "Latin capital letter U with diaeresis and grave",
                "ǜ": "Latin small letter U with diaeresis and grave",
                "ǝ": "Latin small letter Turned E",
                "Ǟ": "Latin capital letter A with diaeresis and macron",
                "ǟ": "Latin small letter A with diaeresis and macron",
                "Ǡ": "Latin capital letter A with dot above and macron",
                "ǡ": "Latin small letter A with dot above and macron",
                "Ǣ": "Latin capital letter Æ with macron",
                "ǣ": "Latin small letter Æ with macron",
                "Ǥ": "Latin capital letter G with stroke",
                "ǥ": "Latin small letter G with stroke",
                "Ǧ": "Latin capital letter G with caron",
                "ǧ": "Latin small letter G with caron",
                "Ǩ": "Latin capital letter K with caron",
                "ǩ": "Latin small letter K with caron",
                "Ǫ": "Latin capital letter O with ogonek",
                "ǫ": "Latin small letter O with ogonek",
                "Ǭ": "Latin capital letter O with ogonek and macron",
                "ǭ": "Latin small letter O with ogonek and macron",
                "Ǯ": "Latin capital letter Ezh with caron",
                "ǯ": "Latin small letter Ezh with caron",
                "ǰ": "Latin small letter J with caron",
                "Ǳ": "Latin capital letter DZ",
                "ǲ": "Latin capital letter D with small letter Z",
                "ǳ": "Latin small letter DZ",
                "Ǵ": "Latin capital letter G with acute",
                "ǵ": "Latin small letter G with acute",
                "Ƕ": "Latin capital letter Hwair",
                "Ƿ": "Latin capital letter Wynn",
                "Ǹ": "Latin capital letter N with grave",
                "ǹ": "Latin small letter N with grave",
                "Ǻ": "Latin capital letter A with ring above and acute",
                "ǻ": "Latin small letter A with ring above and acute",
                "Ǽ": "Latin capital letter Æ with acute",
                "ǽ": "Latin small letter Æ with acute",
                "Ǿ": "Latin capital letter O with stroke and acute",
                "ǿ": "Latin small letter O with stroke and acute",
                "Ȁ": "Latin capital letter A with double grave",
                "ȁ": "Latin small letter A with double grave",
                "Ȃ": "Latin capital letter A with inverted breve",
                "ȃ": "Latin small letter A with inverted breve",
                "Ȅ": "Latin capital letter E with double grave",
                "ȅ": "Latin small letter E with double grave",
                "Ȇ": "Latin capital letter E with inverted breve",
                "ȇ": "Latin small letter E with inverted breve",
                "Ȉ": "Latin capital letter I with double grave",
                "ȉ": "Latin small letter I with double grave",
                "Ȋ": "Latin capital letter I with inverted breve",
                "ȋ": "Latin small letter I with inverted breve",
                "Ȍ": "Latin capital letter O with double grave",
                "ȍ": "Latin small letter O with double grave",
                "Ȏ": "Latin capital letter O with inverted breve",
                "ȏ": "Latin small letter O with inverted breve",
                "Ȑ": "Latin capital letter R with double grave",
                "ȑ": "Latin small letter R with double grave",
                "Ȓ": "Latin capital letter R with inverted breve",
                "ȓ": "Latin small letter R with inverted breve",
                "Ȕ": "Latin capital letter U with double grave",
                "ȕ": "Latin small letter U with double grave",
                "Ȗ": "Latin capital letter U with inverted breve",
                "ȗ": "Latin small letter U with inverted breve",
                "Ș": "Latin capital letter S with comma below",
                "ș": "Latin small letter S with comma below",
                "Ț": "Latin capital letter T with comma below",
                "ț": "Latin small letter T with comma below",
                "Ȝ": "Latin capital letter Yogh",
                "ȝ": "Latin small letter Yogh",
                "Ȟ": "Latin capital letter H with caron",
                "ȟ": "Latin small letter H with caron",
                "Ƞ": "Latin capital letter N with long right leg",
                "ȡ": "Latin small letter D with curl",
                "Ȣ": "Latin capital letter OU",
                "ȣ": "Latin small letter OU",
                "Ȥ": "Latin capital letter Z with hook",
                "ȥ": "Latin small letter Z with hook",
                "Ȧ": "Latin capital letter A with dot above",
                "ȧ": "Latin small letter A with dot above",
                "Ȩ": "Latin capital letter E with cedilla",
                "ȩ": "Latin small letter E with cedilla",
                "Ȫ": "Latin capital letter O with diaeresis and macron",
                "ȫ": "Latin small letter O with diaeresis and macron",
                "Ȭ": "Latin capital letter O with tilde and macron",
                "ȭ": "Latin small letter O with tilde and macron",
                "Ȯ": "Latin capital letter O with dot above",
                "ȯ": "Latin small letter O with dot above",
                "Ȱ": "Latin capital letter O with dot above and macron",
                "ȱ": "Latin small letter O with dot above and macron",
                "Ȳ": "Latin capital letter Y with macron",
                "ȳ": "Latin small letter Y with macron",
                "ȴ": "Latin small letter L with curl",
                "ȵ": "Latin small letter N with curl",
                "ȶ": "Latin small letter T with curl",
                "ȷ": "Latin small letter Dotless J",
                "ȸ": "Latin small letter DB Digraph",
                "ȹ": "Latin small letter QP Digraph",
                "Ⱥ": "Latin capital letter A with stroke",
                "Ȼ": "Latin capital letter C with stroke",
                "ȼ": "Latin small letter C with stroke",
                "Ƚ": "Latin capital letter L with bar",
                "Ⱦ": "Latin capital letter T with diagonal stroke",
                "ȿ": "Latin small letter S with swash tail",
                "ɀ": "Latin small letter Z with swash tail",
                "Ɂ": "Latin capital letter Glottal Stop",
                "ɂ": "Latin small letter Glottal Stop",
                "Ƀ": "Latin capital letter B with stroke",
                "Ʉ": "Latin capital letter U bar",
                "Ʌ": "Latin capital letter Turned V",
                "Ɇ": "Latin capital letter E with stroke",
                "ɇ": "Latin small letter E with stroke",
                "Ɉ": "Latin capital letter J with stroke",
                "ɉ": "Latin small letter J with stroke",
                "Ɋ": "Latin capital letter Q with hook tail",
                "ɋ": "Latin small letter Q with hook tail",
                "Ɍ": "Latin capital letter R with stroke",
                "ɍ": "Latin small letter R with stroke",
                "Ɏ": "Latin capital letter Y with stroke",
                "ɏ": "Latin small letter Y with stroke"]
    }
}
